- name: Install Yaourt
  pacman:
    name:
      - yaourt
    state: present
- name: Install JetBrains Toolbox from AUR
  command: yaourt -S jetbrains-toolbox
  creates: /opt/jetbrains-toolbox
  become: true