- name: Install Python & Pyenv
  pacman:
    name:
      - python
      - pyenv
    state: present

#- name: Add pyenv to bashrc
#  lineinfile:
#    path: ~/.bashrc
#    line: 'export PATH="/usr/local/pyenv/bin:$PATH"'

#- name: Add pyenv init to bashrc
#  lineinfile:
#    path: ~/.bashrc
#    line: 'eval "$(pyenv init -)"'