- name: Run the equivalent of "pacman -Syu"
  become: true
  community.general.pacman:
    update_cache: true

- name: Install common
  become: true
  pacman:
    name:
      - base-devel
      - git
      - glibc
      - lib32-glibc
      - yay
      - yay-bin
      - gedit
    state: present

- name: Yay version
  become: true
  command: yay --version