- name: Set dock position to bottom
  command: gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM

- name: Download Colloid theme
  get_url:
    url: https://github.com/vinceliuice/Colloid-gtk-theme/archive/master.zip
    dest: /tmp/colloid.zip
- name: Extract Colloid theme
  become: true
  unarchive:
    src: /tmp/colloid.zip
    dest: /usr/share/themes
    remote_src: true
    creates: /usr/share/themes/Colloid-gtk-theme-master
