- name: Install Docker
  pacman:
    name: docker
    state: present

- name: Add user to "docker" group
  user:
    name: "{{ lookup('env', 'USER') }}"
    group: "docker"
    append: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Compose
  pip:
    name: docker-compose